language: node_js
addons:
  chrome: stable
node_js:
  - '10'
git:
  depth: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add expo-cli
before_script:
  - yarn codegen
  - yarn danger ci
script:
  - bash scripts/test-deploy.sh
  - yarn lint
  - yarn test:snapshot --requireReference
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy-alpha.sh
  on:
    branch: develop
after_failure:
  - node .loki/upload-failed-image-diffs
cache:
  yarn: true
