version: '3.4' 
services:

  wobbly-frontend-service:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: $DOCKER_IMAGE
    command: bash bin/docker-entrypoint.sh
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "8080:8080"
    environment:
      - BACKEND_URL